'use client';
import { useMemo, useState } from 'react';

type Roadshow={id:string;year:number;date:string;city:string;state:string;group:string;conductor:string;sponsor:string;event:string;venue:string;time:string;duration:string};

export function RoadshowExplorer({data}:{data:Roadshow[]}){
  const [query,setQuery]=useState(''); const [year,setYear]=useState('all'); const [visible,setVisible]=useState(24);
  const years=useMemo(()=>[...new Set(data.map((item)=>item.year))].sort((a,b)=>b-a),[data]);
  const results=useMemo(()=>{const needle=query.trim().toLowerCase();return data.filter((item)=>(year==='all'||item.year===Number(year))&&(!needle||[item.city,item.state,item.venue,item.event,item.sponsor,item.group].join(' ').toLowerCase().includes(needle))).sort((a,b)=>b.year-a.year||a.city.localeCompare(b.city));},[data,query,year]);
  return <section className="explorer-section"><div className="explorer-controls"><label><span>Search a town, venue, event, or sponsor</span><input type="search" value={query} onChange={(event)=>{setQuery(event.target.value);setVisible(24)}} placeholder="Try Bloomington, high school, or USO"/></label><label><span>Year</span><select value={year} onChange={(event)=>{setYear(event.target.value);setVisible(24)}}><option value="all">All years</option>{years.map((item)=><option key={item} value={item}>{item}</option>)}</select></label></div><div className="results-heading" aria-live="polite"><h2>{results.length.toLocaleString()} roadshow {results.length===1?'record':'records'}</h2><p>Newest records are shown first.</p></div>{results.length?<div className="roadshow-list">{results.slice(0,visible).map((item,index)=><article key={`${item.id}-${item.date}-${index}`}><div className="roadshow-date"><strong>{item.year}</strong><span>{item.date.replace(String(item.year),'').replace(/[,\s]+$/,'')||'Date on file'}</span></div><div className="roadshow-place"><h3>{item.city}{item.state?`, ${item.state}`:''}</h3><p>{item.venue||item.event||'Venue not recorded'}</p></div><div className="roadshow-detail"><span>{item.event||item.group||'Performance'}</span>{item.sponsor&&<small>Hosted by {item.sponsor}</small>}</div></article>)}</div>:<div className="empty-results"><h2>No stops match that search.</h2><p>Try a broader town name, venue type, or year.</p></div>}{visible<results.length&&<button className="load-more" onClick={()=>setVisible((count)=>count+24)}>Show 24 more</button>}</section>
}
