'use client';

import Image from 'next/image';
import { siteAsset } from './site-path';

type Props={title:string;subtitle:string;year:string|number;playing:boolean;time:string;duration:string;progress:number;available:boolean;onToggle:()=>void;onStop:()=>void;onPrevious:()=>void;onNext:()=>void;onSeek:(value:number)=>void};

function Readout({title,subtitle,year}:Pick<Props,'title'|'subtitle'|'year'>){return <div className="device-readout"><span>Now selected</span><strong>{title}</strong><b>{year} · {subtitle}</b></div>}
function Scrubber({time,duration,progress,available,onSeek}:Pick<Props,'time'|'duration'|'progress'|'available'|'onSeek'>){return <label className="device-scrubber"><span className="sr-only">Recording position</span><b>{time}</b><input aria-label="Recording position" type="range" min="0" max="1000" value={progress} disabled={!available} onChange={(e)=>onSeek(Number(e.target.value))}/><b>{duration}</b></label>}
function DeviceImage({src,alt}: {src:string;alt:string}){return <div className="device-photo"><Image src={siteAsset(src)} alt={alt} width={1536} height={1024} priority sizes="(max-width: 1000px) 94vw, 52vw"/></div>}

function RadioObject(p:Props){return <section className="media-object device-object radio-v2" aria-label="1950s tabletop radio player"><DeviceImage src="/players/radio-1950s-v2.png" alt="Warm walnut 1950s tabletop radio"/><div className="device-console"><Readout {...p}/><Scrubber {...p}/><div className="radio-v2-controls"><button onClick={p.onToggle} disabled={!p.available}><i/>{p.playing?'Turn radio off':'Turn radio on'}</button><button onClick={p.onNext} disabled={!p.available}><i/>Tune next station</button></div></div></section>}

function HifiObject(p:Props){return <section className="media-object device-object hifi-v2" aria-label="1960s console hi-fi player"><DeviceImage src="/players/hifi-1960s-v2.png" alt="Walnut 1960s console hi-fi with record player"/><div className="device-console"><Readout {...p}/><Scrubber {...p}/><div className="hifi-v2-controls"><button onClick={p.onPrevious} disabled={!p.available}>Previous record</button><button className="primary-device-control" onClick={p.onToggle} disabled={!p.available}>{p.playing?'Lift the needle':'Lower the needle'}</button><button onClick={p.onStop} disabled={!p.available}>Return arm</button><button onClick={p.onNext} disabled={!p.available}>Next record</button></div></div></section>}

function EightTrackObject(p:Props){return <section className="media-object device-object eighttrack-v2" aria-label="1970s eight-track deck player"><DeviceImage src="/players/eight-track-1970s-v2.png" alt="Brushed metal 1970s eight-track stereo deck"/><div className="device-console"><Readout {...p}/><Scrubber {...p}/><div className="eighttrack-v2-controls"><button onClick={p.onPrevious} disabled={!p.available}><span aria-hidden="true">◀◀</span> Previous</button><button onClick={p.onStop} disabled={!p.available}><span aria-hidden="true">■</span> Eject</button><button className="primary-device-control" onClick={p.onToggle} disabled={!p.available}><span aria-hidden="true">{p.playing?'Ⅱ':'▶'}</span> {p.playing?'Pause':'Play'}</button><button onClick={p.onNext} disabled={!p.available}><span aria-hidden="true">▶▶</span> Program</button></div></div></section>}

function BoomboxObject(p:Props){return <section className="media-object device-object boombox-v2" aria-label="1980s cassette boombox player"><DeviceImage src="/players/boombox-1980s-v2.png" alt="Large silver 1980s cassette boombox"/><div className="device-console"><Readout {...p}/><Scrubber {...p}/><div className="boombox-v2-controls"><button onClick={p.onPrevious} disabled={!p.available}><span aria-hidden="true">◀◀</span> Rewind</button><button className="primary-device-control" onClick={p.onToggle} disabled={!p.available}><span aria-hidden="true">{p.playing?'Ⅱ':'▶'}</span> {p.playing?'Pause':'Play tape'}</button><button onClick={p.onStop} disabled={!p.available}><span aria-hidden="true">■</span> Stop</button><button onClick={p.onNext} disabled={!p.available}><span aria-hidden="true">▶▶</span> Fast forward</button></div></div></section>}

function DiscObject(p:Props){return <section className="media-object device-object disc-v2" aria-label="1990s portable compact disc player"><DeviceImage src="/players/discman-1990s-v2.png" alt="Silver 1990s portable compact disc player with headphones"/><div className="device-console"><Readout {...p}/><Scrubber {...p}/><div className="disc-v2-controls"><button onClick={p.onPrevious} disabled={!p.available}>Back</button><button className="primary-device-control" onClick={p.onToggle} disabled={!p.available}>{p.playing?'Pause CD':'Play CD'}</button><button onClick={p.onStop} disabled={!p.available}>Stop</button><button onClick={p.onNext} disabled={!p.available}>Next track</button></div></div></section>}

function PocketObject(p:Props){return <section className="media-object device-object pocket-v2" aria-label="2000s pocket music player"><DeviceImage src="/players/pocket-2000s-v2.png" alt="White early-2000s pocket music player with click wheel"/><div className="device-console"><Readout {...p}/><Scrubber {...p}/><div className="pocket-v2-controls"><button onClick={p.onPrevious} disabled={!p.available}>Previous</button><button className="primary-device-control round" onClick={p.onToggle} disabled={!p.available}>{p.playing?'Pause':'Play'}</button><button onClick={p.onNext} disabled={!p.available}>Next</button></div></div></section>}

function StreamingObject(p:Props){return <section className="media-object device-object touch-v2" aria-label="Modern touchscreen music player"><DeviceImage src="/players/touch-2010s-v2.png" alt="Modern touchscreen player on a walnut listening stand"/><div className="device-console"><Readout {...p}/><Scrubber {...p}/><div className="touch-v2-controls"><button onClick={p.onPrevious} disabled={!p.available}>Previous song</button><button className="primary-device-control round" onClick={p.onToggle} disabled={!p.available}>{p.playing?'Pause':'Play'}</button><button onClick={p.onNext} disabled={!p.available}>Next song</button></div></div></section>}

export function EraObject({era,...props}:Props&{era:string}){if(era==='1950s')return <RadioObject {...props}/>;if(era==='1960s')return <HifiObject {...props}/>;if(era==='1970s')return <EightTrackObject {...props}/>;if(era==='1980s')return <BoomboxObject {...props}/>;if(era==='1990s')return <DiscObject {...props}/>;if(era==='2000s')return <PocketObject {...props}/>;return <StreamingObject {...props}/>}
